--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyFactions
branches:
  - master
projects:
  PiggyFactions:
    path: ""
    icon: "resources/PiggyFactions-icon.png"
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
      - src: DaPigGuy/FormAPI-4.0.0/libFormAPI
        version: ^2.1.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.0
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint:
      phpstan: false
...
