--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyFactions
branches:
  - master
projects:
  PiggyFactions:
    path: ""
    icon: "resources/PiggyFactions-icon.png"
    libs:
      - src: Paroxity/Commando/Commando
        version: ^2.1.0
      - src: poggit/libasynql/libasynql
        version: ^3.3.1
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^2.0.0
    lint:
      phpstan: false
...