--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyFactions
branches:
  - master
projects:
  PiggyFactions:
    path: ""
    icon: "resources/PiggyFactions-icon.png"
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.2
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint: false
...
