name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: wget PiggyCustomEnchants
        uses: wei/wget@v1
        with:
          args: -O vendor/PiggyCustomEnchants.phar https://poggit.pmmp.io/r/82514/PiggyCustomEnchants_dev-439.phar
      - name: wget HRKChat
        uses: wei/wget@v1
        with:
          args: -O vendor/HRKChat.phar https://poggit.pmmp.io/r/80529/HRKChat_dev-31.phar
      - name: wget Hierarchy
        uses: wei/wget@v1
        with:
          args: -O vendor/Hierarchy.phar https://poggit.pmmp.io/r/81611/Hierarchy_dev-81.phar
      - name: wget virions, libasynql
        uses: wei/wget@v1
        with:
          args: -O vendor/libasynql.phar https://poggit.pmmp.io/r/81738/libasynql_dev-119.phar
      - name: wget virions, FormAPI
        uses: wei/wget@v1
        with:
          args: -O vendor/FormAPI.phar https://poggit.pmmp.io/r/54589/FormApi_dev-9.phar
      - name: wget virions, libPiggyEconomy
        uses: wei/wget@v1
        with:
          args: -O vendor/libPiggyEconomy.phar https://poggit.pmmp.io/r/78540/libPiggyEconomy_dev-7.phar
      - name: wget virions, Commando
        uses: wei/wget@v1
        with:
          args: -O vendor/Commando.phar https://poggit.pmmp.io/r/80537/Commando_dev-29.phar
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist