name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: mkdir vendor
      - name: Download Plugin Dependencies
        run: |
          wget -O vendor/PiggyCustomEnchants.phar https://poggit.pmmp.io/r/94443/PiggyCustomEnchants_dev-468.phar
          wget -O vendor/HRKChat.phar https://poggit.pmmp.io/r/80529/HRKChat_dev-31.phar
          wget -O vendor/Hierarchy.phar https://poggit.pmmp.io/r/81611/Hierarchy_dev-81.phar
          wget -O vendor/ScoreHud.phar https://poggit.pmmp.io/r/161570/ScoreHud_dev-71.phar
      - name: Download Virion Dependencies
        run: |
          wget -O vendor/libasynql.phar https://poggit.pmmp.io/r/213142/libasynql_dev-203.phar
          wget -O vendor/FormsUI.phar https://poggit.pmmp.io/r/209836/FormsUI_dev-20.phar
          wget -O vendor/libPiggyEconomy.phar https://poggit.pmmp.io/r/212853/libPiggyEconomy_dev-19.phar
          wget -O vendor/libPiggyUpdateChecker.phar https://poggit.pmmp.io/r/163495/libPiggyUpdateChecker_dev-1.phar
          wget -O vendor/Commando.phar https://poggit.pmmp.io/r/216831/Commando_dev-34.phar
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@5.3.0
        with:
          phpstan-config: phpstan.neon.dist
