name: PHPStan 4.0.0

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: mkdir vendor
      - name: Download Plugin Dependencies
        run: |
          wget -O vendor/PiggyCustomEnchants.phar https://poggit.pmmp.io/r/94443/PiggyCustomEnchants_dev-468.phar
          wget -O vendor/HRKChat.phar https://poggit.pmmp.io/r/80529/HRKChat_dev-31.phar
          wget -O vendor/Hierarchy.phar https://poggit.pmmp.io/r/81611/Hierarchy_dev-81.phar
          wget -O vendor/ScoreHud.phar https://poggit.pmmp.io/r/134708/ScoreHud_dev-70.phar
      - name: Download Virion Dependencies
        run: |
          wget -O vendor/libasynql.phar https://poggit.pmmp.io/r/159125/libasynql_dev-174.phar
          wget -O vendor/FormAPI.phar https://poggit.pmmp.io/r/77082/FormAPI_dev-1.phar
          wget -O vendor/libPiggyEconomy.phar https://poggit.pmmp.io/r/94380/libPiggyEconomy_dev-10.phar
          wget -O vendor/Commando.phar https://poggit.pmmp.io/r/94451/Commando_dev-3.phar
      - name: Run PHPStan
        uses: paroxity/pmmp-phpstan-action@4.2.0
        with:
          phpstan-config: phpstan.neon.dist
